const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwlB-XvmuGM7DWDqHtLIhrkeXlEwJ3iabaELeyf4MVcv9UgMFlLxgg9oqgwhtRgb3P5FQ/exec";
const ADMIN_ID = "8405877507";
const ADMIN_PASSWORD = "Diksha@197781";
const APPLICATIONS_KEY = "diksha_applications_v2";

const loginModal=document.getElementById("loginModal");
const userModal=document.getElementById("userModal");
function openLogin(){loginModal.classList.add("show");document.getElementById("loginError").textContent="";document.getElementById("username").focus();}
document.getElementById("loginBtn").onclick=openLogin;
document.getElementById("loginBtn2").onclick=openLogin;
document.getElementById("closeLogin").onclick=()=>loginModal.classList.remove("show");
document.getElementById("closeUser").onclick=()=>userModal.classList.remove("show");
document.getElementById("doLogin").onclick=async()=>{
 const username=document.getElementById("username").value.trim(); const password=document.getElementById("password").value; const error=document.getElementById("loginError"); error.textContent="";
 if(username!==ADMIN_ID || password!==ADMIN_PASSWORD){error.textContent="Admin ID या Password गलत है।";return;}
 loginModal.classList.remove("show"); document.getElementById("userWelcomeName").textContent="Welcome, Admin"; document.getElementById("userDashUsername").textContent=ADMIN_ID; document.getElementById("userDashMobile").textContent=ADMIN_ID; document.getElementById("password").value=""; userModal.classList.add("show"); await renderApplications();
};
document.getElementById("userLogout").onclick=()=>{userModal.classList.remove("show");document.getElementById("adminApplications").innerHTML="";};
function getApplications(){try{return JSON.parse(localStorage.getItem(APPLICATIONS_KEY)||"[]")}catch{return[]}}
function saveApplications(a){localStorage.setItem(APPLICATIONS_KEY,JSON.stringify(a))}
function createApplicationNumber(){const n=new Date();return `DCC-${n.getFullYear()}${String(n.getMonth()+1).padStart(2,"0")}${String(n.getDate()).padStart(2,"0")}-${String(n.getTime()).slice(-6)}-${Math.floor(100+Math.random()*900)}`}
function fetchApplicationsFromGoogle(){return new Promise((resolve,reject)=>{const cb="dikshaApps_"+Date.now()+"_"+Math.floor(Math.random()*9999);const sc=document.createElement("script");let done=false;const timer=setTimeout(()=>finish(new Error("Google Sheets से connection नहीं हो पाया।")),15000);function cleanup(){clearTimeout(timer);delete window[cb];sc.remove()}function finish(err,data){if(done)return;done=true;cleanup();err?reject(err):resolve(data)}window[cb]=d=>{if(!d||!d.success)return finish(new Error(d&&d.error||"Google Sheets error."));finish(null,Array.isArray(d.applications)?d.applications:[])};sc.onerror=()=>finish(new Error("Google Apps Script URL उपलब्ध नहीं है।"));sc.src=GOOGLE_SCRIPT_URL+"?callback="+encodeURIComponent(cb)+"&_="+Date.now();document.head.appendChild(sc)})}
function postToGoogle(data){return new Promise((resolve,reject)=>{const name="dikshaPost_"+Date.now();const iframe=document.createElement("iframe");iframe.name=name;iframe.style.display="none";document.body.appendChild(iframe);const form=document.createElement("form");form.method="POST";form.action=GOOGLE_SCRIPT_URL;form.target=name;form.style.display="none";Object.entries(data).forEach(([k,v])=>{const i=document.createElement("input");i.type="hidden";i.name=k;i.value=v??"";form.appendChild(i)});document.body.appendChild(form);let finished=false;const finish=(ok)=>{if(finished)return;finished=true;form.remove();setTimeout(()=>iframe.remove(),500);ok?resolve({success:true}):reject(new Error("Google Sheets request failed."))};iframe.onload=()=>finish(true);iframe.onerror=()=>finish(false);form.submit();setTimeout(()=>finish(true),3000)})}
function updateAdminStats(apps){const a=Array.isArray(apps)?apps:getApplications();document.getElementById("adminTotalApplications").textContent=a.length;document.getElementById("adminNewApplications").textContent=a.filter(x=>(x.status||"New")==="New").length;document.getElementById("adminProcessingApplications").textContent=a.filter(x=>(x.status||"New")==="Processing").length;document.getElementById("adminCompletedApplications").textContent=a.filter(x=>(x.status||"New")==="Completed").length}
async function renderApplications(){const box=document.getElementById("adminApplications");box.innerHTML='<div class="admin-empty">Loading applications...</div>';try{const apps=await fetchApplicationsFromGoogle();saveApplications(apps);updateAdminStats(apps);const search=document.getElementById("applicationSearch").value.trim().toLowerCase();const filter=document.getElementById("applicationStatusFilter").value;const filtered=apps.filter(a=>{const hay=[a.applicationNo,a.name,a.mobile,a.whatsapp,a.reason].join(" ").toLowerCase();return(!search||hay.includes(search))&&(!filter||(a.status||"New")===filter)}).slice().reverse();if(!filtered.length){box.innerHTML='<div class="admin-empty">No applications received yet.</div>';return}box.innerHTML='<h3>APPLICATIONS <small class="result-count">'+filtered.length+' shown</small></h3>'+filtered.map(a=>{const st=a.status||"New";return `<div class="admin-item"><div><b>${escapeHtml(a.applicationNo)}</b> <small>${escapeHtml(a.createdAt)}</small></div><p><b>Name:</b> ${escapeHtml(a.name)}</p><p><b>Mobile:</b> ${escapeHtml(a.mobile)} &nbsp; <b>WhatsApp:</b> ${escapeHtml(a.whatsapp)}</p><p><b>Apply For:</b> ${escapeHtml(a.reason)}</p><div class="admin-row-actions"><select class="status-select" data-app-no="${escapeHtml(a.applicationNo)}">${["New","Processing","Completed"].map(x=>`<option ${x===st?"selected":""}>${x}</option>`).join("")}</select><button class="secondary print-app" data-app-no="${escapeHtml(a.applicationNo)}">Print</button><button class="secondary delete-app" data-app-no="${escapeHtml(a.applicationNo)}">Delete</button></div></div>`}).join("");box.querySelectorAll(".status-select").forEach(sel=>sel.onchange=async()=>{const no=sel.dataset.appNo,st=sel.value;sel.disabled=true;try{await postToGoogle({action:"status",applicationNo:no,status:st});const local=getApplications();const item=local.find(x=>x.applicationNo===no);if(item)item.status=st;saveApplications(local);updateAdminStats(local)}catch(e){alert("Status update failed: "+e.message);await renderApplications()}finally{sel.disabled=false}});box.querySelectorAll(".print-app").forEach(b=>b.onclick=()=>printApplication(apps.find(a=>a.applicationNo===b.dataset.appNo)));box.querySelectorAll(".delete-app").forEach(b=>b.onclick=async()=>{const no=b.dataset.appNo;if(!confirm("Delete this application from Google Sheet?"))return;b.disabled=true;try{await postToGoogle({action:"delete",applicationNo:no});await renderApplications()}catch(e){alert("Delete failed: "+e.message);b.disabled=false}})}catch(e){updateAdminStats();box.innerHTML='<div class="admin-empty">Google Sheets से applications load नहीं हो पाईं।<br>'+escapeHtml(e.message)+'</div>'}}
document.getElementById("viewApplications").onclick=renderApplications;document.getElementById("refreshApplications").onclick=renderApplications;document.getElementById("applicationSearch").addEventListener("input",renderApplications);document.getElementById("applicationStatusFilter").addEventListener("change",renderApplications);
function printApplication(a){if(!a)return;const w=window.open("","_blank","width=800,height=900");if(!w){alert("Please allow pop-ups to print the application.");return}w.document.write(`<!doctype html><html><head><title>${escapeHtml(a.applicationNo)}</title><style>body{font-family:Arial;padding:30px}.head{text-align:center;border-bottom:2px solid #073d91;padding-bottom:15px}.box{margin-top:25px;border:1px solid #ccd6e2}.row{display:grid;grid-template-columns:35% 65%;padding:13px;border-bottom:1px solid #e5ebf2}.label{font-weight:bold}</style></head><body><div class="head"><h1>DIKSHA COMPUTER CENTER</h1><h2>BALAM MADHEPURA</h2><b>APPLICATION / VISIT RECEIPT</b></div><div class="box"><div class="row"><div class="label">Application No.</div><div>${escapeHtml(a.applicationNo)}</div></div><div class="row"><div class="label">Name</div><div>${escapeHtml(a.name)}</div></div><div class="row"><div class="label">Mobile</div><div>${escapeHtml(a.mobile)}</div></div><div class="row"><div class="label">WhatsApp</div><div>${escapeHtml(a.whatsapp)}</div></div><div class="row"><div class="label">Apply For</div><div>${escapeHtml(a.reason)}</div></div><div class="row"><div class="label">Date & Time</div><div>${escapeHtml(a.createdAt)}</div></div><div class="row"><div class="label">Status</div><div>${escapeHtml(a.status||"New")}</div></div></div><br><button onclick="window.print()">Print</button></body></html>`);w.document.close()}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
const applyModal=document.getElementById("applyModal"),receiptModal=document.getElementById("receiptModal"),applyForm=document.getElementById("applyForm"),applyReason=document.getElementById("applyReason"),applyOtherReason=document.getElementById("applyOtherReason");
function openApply(){receiptModal.classList.remove("show");applyModal.classList.add("show");document.getElementById("applyError").textContent=""}function closeApply(){applyModal.classList.remove("show")}document.querySelectorAll('a[href="#applyNow"]').forEach(x=>x.addEventListener("click",e=>{e.preventDefault();openApply()}));document.getElementById("closeApply").onclick=closeApply;document.getElementById("closeReceipt").onclick=()=>receiptModal.classList.remove("show");applyReason.addEventListener("change",()=>{const o=applyReason.value==="Other";applyOtherReason.classList.toggle("show",o);applyOtherReason.required=o;if(!o)applyOtherReason.value=""});
applyForm.addEventListener("submit",async e=>{e.preventDefault();const name=document.getElementById("applyName").value.trim(),mobile=document.getElementById("applyMobile").value.replace(/\D/g,""),whatsapp=document.getElementById("applyWhatsapp").value.replace(/\D/g,""),selected=applyReason.value,reason=selected==="Other"?applyOtherReason.value.trim():selected,error=document.getElementById("applyError"),btn=applyForm.querySelector('button[type="submit"]');error.textContent="";if(name.length<2){error.textContent="Please enter your full name.";return}if(!/^\d{10}$/.test(mobile)){error.textContent="Please enter a valid 10-digit Mobile Number.";return}if(!/^\d{10}$/.test(whatsapp)){error.textContent="Please enter a valid 10-digit WhatsApp Number.";return}if(!reason){error.textContent="Please select a service.";return}const app={applicationNo:createApplicationNumber(),name,mobile,whatsapp,reason,status:"New",createdAt:new Date().toLocaleString("en-IN")};btn.disabled=true;const old=btn.textContent;btn.textContent="Submitting...";try{await postToGoogle(app);const local=getApplications();local.push(app);saveApplications(local);document.getElementById("receiptNo").textContent=app.applicationNo;document.getElementById("receiptName").textContent=app.name;document.getElementById("receiptMobile").textContent=app.mobile;document.getElementById("receiptWhatsapp").textContent=app.whatsapp;document.getElementById("receiptReason").textContent=app.reason;document.getElementById("receiptDate").textContent=app.createdAt;applyModal.classList.remove("show");receiptModal.classList.add("show");applyForm.reset();applyOtherReason.classList.remove("show");applyOtherReason.required=false}catch(err){error.textContent="Application submit nahi ho paya. Google Apps Script deployment check karein.";console.error(err)}finally{btn.disabled=false;btn.textContent=old}});
document.getElementById("printReceipt").onclick=()=>window.print();document.getElementById("newApplication").onclick=()=>{receiptModal.classList.remove("show");applyForm.reset();applyOtherReason.classList.remove("show");applyOtherReason.required=false;applyModal.classList.add("show")};
[loginModal,userModal,applyModal,receiptModal].forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("show")}));
